#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("scanbotsdkexamplexamarin.Droid.Resource", IsApplication=true)]

namespace scanbotsdkexamplexamarin.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ScanbotSDK.Xamarin.Android.Resource.Array.document_types = global::scanbotsdkexamplexamarin.Droid.Resource.Array.document_types;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.cornerImageSrc = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.cornerImageSrc;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.edgeColor = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.edgeColor;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.edgeImageSrc = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.edgeImageSrc;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.editPolygonHandleSize = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.editPolygonHandleSize;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.editPolygonMagnifier = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.editPolygonMagnifier;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.editPolygonStrokeWidth = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.editPolygonStrokeWidth;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.magneticLineTreshold = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.magneticLineTreshold;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.magnifierCrossSize = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.magnifierCrossSize;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.magnifierCrossStrokeWidth = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.magnifierCrossStrokeWidth;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.magnifierImageSrc = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.magnifierImageSrc;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.magnifierMargin = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.magnifierMargin;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.magnifierRadius = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.magnifierRadius;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.magnifierStrokeWidth = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.magnifierStrokeWidth;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.polygonFillColor = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.polygonFillColor;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.polygonStrokeColor = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.polygonStrokeColor;
			global::ScanbotSDK.Xamarin.Android.Resource.Attribute.polygonStrokeWidth = global::scanbotsdkexamplexamarin.Droid.Resource.Attribute.polygonStrokeWidth;
			global::ScanbotSDK.Xamarin.Android.Resource.Dimension.document_thumbnail_size = global::scanbotsdkexamplexamarin.Droid.Resource.Dimension.document_thumbnail_size;
			global::ScanbotSDK.Xamarin.Android.Resource.Dimension.edit_polygon_handle_size = global::scanbotsdkexamplexamarin.Droid.Resource.Dimension.edit_polygon_handle_size;
			global::ScanbotSDK.Xamarin.Android.Resource.Dimension.magnetic_line_treshold = global::scanbotsdkexamplexamarin.Droid.Resource.Dimension.magnetic_line_treshold;
			global::ScanbotSDK.Xamarin.Android.Resource.Dimension.magnifier_cross_size = global::scanbotsdkexamplexamarin.Droid.Resource.Dimension.magnifier_cross_size;
			global::ScanbotSDK.Xamarin.Android.Resource.Dimension.magnifier_cross_stroke_width = global::scanbotsdkexamplexamarin.Droid.Resource.Dimension.magnifier_cross_stroke_width;
			global::ScanbotSDK.Xamarin.Android.Resource.Dimension.magnifier_margin = global::scanbotsdkexamplexamarin.Droid.Resource.Dimension.magnifier_margin;
			global::ScanbotSDK.Xamarin.Android.Resource.Dimension.magnifier_raduis = global::scanbotsdkexamplexamarin.Droid.Resource.Dimension.magnifier_raduis;
			global::ScanbotSDK.Xamarin.Android.Resource.Dimension.magnifier_stroke_width = global::scanbotsdkexamplexamarin.Droid.Resource.Dimension.magnifier_stroke_width;
			global::ScanbotSDK.Xamarin.Android.Resource.Dimension.polygon_stroke_width = global::scanbotsdkexamplexamarin.Droid.Resource.Dimension.polygon_stroke_width;
			global::ScanbotSDK.Xamarin.Android.Resource.Dimension.touch_focus_polygon_width = global::scanbotsdkexamplexamarin.Droid.Resource.Dimension.touch_focus_polygon_width;
			global::ScanbotSDK.Xamarin.Android.Resource.String.camera_configuration = global::scanbotsdkexamplexamarin.Droid.Resource.String.camera_configuration;
			global::ScanbotSDK.Xamarin.Android.Resource.String.device_configuration = global::scanbotsdkexamplexamarin.Droid.Resource.String.device_configuration;
			global::ScanbotSDK.Xamarin.Android.Resource.String.library_name = global::scanbotsdkexamplexamarin.Droid.Resource.String.library_name;
			global::ScanbotSDK.Xamarin.Android.Resource.String.support_email_template = global::scanbotsdkexamplexamarin.Droid.Resource.String.support_email_template;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_htc_htc_mecha = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_htc_htc_mecha;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_htc_m7 = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_htc_m7;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_motorola_xt910_rtanz = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_motorola_xt910_rtanz;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_corsicadd = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_corsicadd;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_d2att = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_d2att;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_d2spr = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_d2spr;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_d2tmo = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_d2tmo;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_d2uc = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_d2uc;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_d2vzw = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_d2vzw;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_gd1wifiue = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_gd1wifiue;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_ja3gxx = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_ja3gxx;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_jflteuc = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_jflteuc;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_kyleproxx = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_kyleproxx;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_m0xx = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_m0xx;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_m3xx = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_m3xx;
			global::ScanbotSDK.Xamarin.Android.Resource.Xml.cwac_camera_profile_samsung_yakju = global::scanbotsdkexamplexamarin.Droid.Resource.Xml.cwac_camera_profile_samsung_yakju;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.EditPolygonImageView = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.EditPolygonImageView;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.EditPolygonImageView_cornerImageSrc = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.EditPolygonImageView_cornerImageSrc;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.EditPolygonImageView_edgeColor = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.EditPolygonImageView_edgeColor;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.EditPolygonImageView_edgeImageSrc = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.EditPolygonImageView_edgeImageSrc;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.EditPolygonImageView_editPolygonHandleSize = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.EditPolygonImageView_editPolygonHandleSize;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.EditPolygonImageView_editPolygonStrokeWidth = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.EditPolygonImageView_editPolygonStrokeWidth;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.EditPolygonImageView_magneticLineTreshold = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.EditPolygonImageView_magneticLineTreshold;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.MagnifierView = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.MagnifierView;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.MagnifierView_editPolygonMagnifier = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.MagnifierView_editPolygonMagnifier;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.MagnifierView_magnifierCrossSize = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.MagnifierView_magnifierCrossSize;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.MagnifierView_magnifierCrossStrokeWidth = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.MagnifierView_magnifierCrossStrokeWidth;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.MagnifierView_magnifierImageSrc = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.MagnifierView_magnifierImageSrc;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.MagnifierView_magnifierMargin = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.MagnifierView_magnifierMargin;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.MagnifierView_magnifierRadius = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.MagnifierView_magnifierRadius;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.MagnifierView_magnifierStrokeWidth = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.MagnifierView_magnifierStrokeWidth;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.PolygonView = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.PolygonView;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.PolygonView_polygonFillColor = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.PolygonView_polygonFillColor;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.PolygonView_polygonStrokeColor = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.PolygonView_polygonStrokeColor;
			global::ScanbotSDK.Xamarin.Android.Resource.Styleable.PolygonView_polygonStrokeWidth = global::scanbotsdkexamplexamarin.Droid.Resource.Styleable.PolygonView_polygonStrokeWidth;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int document_types = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int cornerImageSrc = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int edgeColor = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int edgeImageSrc = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int editPolygonHandleSize = 2130771970;
			
			// aapt resource value: 0x7f010007
			public const int editPolygonMagnifier = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int editPolygonStrokeWidth = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int magneticLineTreshold = 2130771969;
			
			// aapt resource value: 0x7f010008
			public const int magnifierCrossSize = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int magnifierCrossStrokeWidth = 2130771977;
			
			// aapt resource value: 0x7f010006
			public const int magnifierImageSrc = 2130771974;
			
			// aapt resource value: 0x7f01000c
			public const int magnifierMargin = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int magnifierRadius = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int magnifierStrokeWidth = 2130771978;
			
			// aapt resource value: 0x7f01000f
			public const int polygonFillColor = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int polygonStrokeColor = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int polygonStrokeWidth = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int document_thumbnail_size = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int edit_polygon_handle_size = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int magnetic_line_treshold = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int magnifier_cross_size = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int magnifier_cross_stroke_width = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int magnifier_margin = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int magnifier_raduis = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int magnifier_stroke_width = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int polygon_stroke_width = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int touch_focus_polygon_width = 2131230729;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ui_crop_corner_handle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ui_crop_magnifier = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ui_crop_side_handle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ui_edit_ico_cancel = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ui_edit_ico_save = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090010
			public const int applyImageFilterButton = 2131296272;
			
			// aapt resource value: 0x7f090006
			public const int cancelButton = 2131296262;
			
			// aapt resource value: 0x7f090012
			public const int copyrightTextView = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int createPdfButton = 2131296273;
			
			// aapt resource value: 0x7f09000e
			public const int croppingUIButton = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int documentDetectionButton = 2131296271;
			
			// aapt resource value: 0x7f090007
			public const int doneButton = 2131296263;
			
			// aapt resource value: 0x7f09000c
			public const int imageView = 2131296268;
			
			// aapt resource value: 0x7f09000a
			public const int processImageProgressBar = 2131296266;
			
			// aapt resource value: 0x7f090000
			public const int scanbotCameraView = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int scanbotEditImageView = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int scanbotFlashButton = 2131296260;
			
			// aapt resource value: 0x7f090009
			public const int scanbotMagnifierView = 2131296265;
			
			// aapt resource value: 0x7f090001
			public const int scanbotPolygonView = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int scanbotResultImageView = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int scanbotSnapButton = 2131296259;
			
			// aapt resource value: 0x7f09000d
			public const int scanningUIButton = 2131296269;
			
			// aapt resource value: 0x7f09000b
			public const int scrollView1 = 2131296267;
			
			// aapt resource value: 0x7f090005
			public const int userGuidanceTextView = 2131296261;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int CameraViewDemo = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CroppingActionBarView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int CroppingImageDemo = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060005
			public const int app_name = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int camera_configuration = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int device_configuration = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int hello = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int support_email_template = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int cwac_camera_profile_htc_htc_mecha = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cwac_camera_profile_htc_m7 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cwac_camera_profile_motorola_xt910_rtanz = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cwac_camera_profile_samsung_corsicadd = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int cwac_camera_profile_samsung_d2att = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int cwac_camera_profile_samsung_d2spr = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int cwac_camera_profile_samsung_d2tmo = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int cwac_camera_profile_samsung_d2uc = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int cwac_camera_profile_samsung_d2vzw = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int cwac_camera_profile_samsung_gd1wifiue = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int cwac_camera_profile_samsung_ja3gxx = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int cwac_camera_profile_samsung_jflteuc = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int cwac_camera_profile_samsung_kyleproxx = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int cwac_camera_profile_samsung_m0xx = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int cwac_camera_profile_samsung_m3xx = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int cwac_camera_profile_samsung_yakju = 2131034127;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] EditPolygonImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 4
			public const int EditPolygonImageView_cornerImageSrc = 4;
			
			// aapt resource value: 3
			public const int EditPolygonImageView_edgeColor = 3;
			
			// aapt resource value: 5
			public const int EditPolygonImageView_edgeImageSrc = 5;
			
			// aapt resource value: 2
			public const int EditPolygonImageView_editPolygonHandleSize = 2;
			
			// aapt resource value: 0
			public const int EditPolygonImageView_editPolygonStrokeWidth = 0;
			
			// aapt resource value: 1
			public const int EditPolygonImageView_magneticLineTreshold = 1;
			
			public static int[] MagnifierView = new int[]
			{
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 1
			public const int MagnifierView_editPolygonMagnifier = 1;
			
			// aapt resource value: 2
			public const int MagnifierView_magnifierCrossSize = 2;
			
			// aapt resource value: 3
			public const int MagnifierView_magnifierCrossStrokeWidth = 3;
			
			// aapt resource value: 0
			public const int MagnifierView_magnifierImageSrc = 0;
			
			// aapt resource value: 6
			public const int MagnifierView_magnifierMargin = 6;
			
			// aapt resource value: 5
			public const int MagnifierView_magnifierRadius = 5;
			
			// aapt resource value: 4
			public const int MagnifierView_magnifierStrokeWidth = 4;
			
			public static int[] PolygonView = new int[]
			{
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 2
			public const int PolygonView_polygonFillColor = 2;
			
			// aapt resource value: 1
			public const int PolygonView_polygonStrokeColor = 1;
			
			// aapt resource value: 0
			public const int PolygonView_polygonStrokeWidth = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
