#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ClassicalComponentsDemo.Droid.Resource", IsApplication=true)]

namespace ClassicalComponentsDemo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int ui_crop_corner_handle = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int ui_crop_magnifier = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ui_crop_side_handle = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ui_edit_ico_cancel = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int ui_edit_ico_save = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int ui_edit_rotate = 2130771973;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int applyImageFilterButton = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int autoSnappingToggleButton = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int businessCardButton = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int businessCardImage = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int businessCardText = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int camera = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int cancelButton = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int content = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int copyrightTextView = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int createPdfButton = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int createTiffButton = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int croppingUIButton = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int doneButton = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int flash = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int imageProcessingProgress = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int imageView = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int importImageButton = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int item = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int page = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int pages_preview = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int performOcrButton = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int polygonView = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int processImageProgressBar = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int progressView = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int rotateCWButton = 2130837528;
			
			// aapt resource value: 0x7F02001D
			public const int scanbotCameraView = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int scanbotEditImageToolbar = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int scanbotEditImageView = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int scanbotFlashButton = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int scanbotMagnifierView = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int scanbotPolygonView = 2130837538;
			
			// aapt resource value: 0x7F020019
			public const int scanDisabilityCertificateButton = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int scanMrzButton = 2130837530;
			
			// aapt resource value: 0x7F020023
			public const int scanningUIButton = 2130837539;
			
			// aapt resource value: 0x7F02001B
			public const int scanPayformButton = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int scanQrCodeAndDocumentButton = 2130837532;
			
			// aapt resource value: 0x7F020024
			public const int scrollView1 = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int shutterButton = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int snap = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int snapped_message = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int userGuidanceTextView = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int workflowResultsLayout = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int workflowsButton = 2130837546;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int BusinessCardPreview = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int BusinessCardsLayout = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int BusinessCardsPreview = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int CameraViewDemo = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int CroppingActionBarView = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int CroppingImageDemo = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int ItemPage = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int WorkflowsMenu = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int Icon = 2130968576;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
