// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace scanbotsdkexamplexamarin.iOS
{
	public partial class WorkflowResultsCollectionViewCell : UICollectionViewCell
	{
		public WorkflowResultsCollectionViewCell (IntPtr handle) : base (handle)
		{
		}

        public UIImageView ImageView {
            get 
            {
                return this.imageView;
            } 

            set 
            { 
                this.imageView = value;
            } 
        }
    }
}
